// Neural texture decoding — one MLP evaluation per screen pixel (compute pass).
// Results are cached in a 2D-array texture (4 channels per layer) and reused by view.wgsl
// until zoom / pan / canvas size change. Constants between {{ }} are filled by main.js.

const OUT4 : u32 = {{OUT4}};             // decoded channels / 4 (rounded up)

struct View {
  zoom    : f32,
  centerX : f32,
  centerY : f32,
  aspect  : f32,
  size    : vec2u,                     // output size in pixels
};

@group(0) @binding(0) var samp   : sampler;
@group(0) @binding(1) var grid0  : texture_2d_array<f32>;
@group(0) @binding(2) var grid1  : texture_2d_array<f32>;
@group(0) @binding(3) var<{{W_SPACE}}> W : array<vec4f, {{W_LEN}}>;   // packed by mlp.js
@group(0) @binding(4) var<uniform> V : View;
@group(0) @binding(5) var outTex : texture_storage_2d_array<rgba16float, write>;

// Latent lookups (dequantize [0,1] -> [-1,1]) + MLP, generated by mlp.js.
{{MLP}}

@compute @workgroup_size(8, 8)
fn cs(@builtin(global_invocation_id) id : vec3u) {
  if (any(id.xy >= V.size)) { return; }
  let s = (vec2f(id.xy) + 0.5) / vec2f(V.size);
  let uv = vec2f(V.centerX, V.centerY) + (s - 0.5) * vec2f(V.aspect, 1.0) / V.zoom;
  if (any(uv < vec2f(0.0)) || any(uv > vec2f(1.0))) { return; }   // view.wgsl draws the border
  let d = mlp(uv);
  for (var l = 0u; l < OUT4; l++) { textureStore(outTex, id.xy, l, d[l]); }
}
